<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2016-02-16T09:57:03+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      timezone
 * @group     app
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'timezone' => 'Europe/London',
);
