<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2017-08-05T14:06:47+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      linkedin.email_filters.blacklist
 * @group     auth
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'linkedin' => array(
        'appid' => '77zbbw4ax3rzlv',
        'secret' => 'WkgyfEEYelwmp5fI',
        'registration' => array(
            'enabled' => true,
            'group' => 1,
        ),
        'email_filters' => array(
            'whitelist' => array(
            ),
            'blacklist' => array(
            ),
        ),
    ),
);
