<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2017-12-07T18:28:05+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.latest_version
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'site' => 'Businessmodelzoo Alpha',
    'version_installed' => '5.7.5.6',
    'misc' => array(
        'access_entity_updated' => 1456326039,
        'user_timezones' => false,
        'latest_version' => '5.7.5.13',
        'do_page_reindex_check' => false,
        'modern_tile_thumbnail_fid' => '13',
        'modern_tile_thumbnail_bgcolor' => '',
        'iphone_home_screen_thumbnail_fid' => '14',
        'favicon_fid' => '15',
    ),
    'accessibility' => array(
        'toolbar_titles' => true,
        'toolbar_large_font' => false,
        'display_help_system' => false,
    ),
    'editor' => array(
        'concrete' => array(
            'enable_filemanager' => '1',
            'enable_sitemap' => '1',
        ),
        'plugins' => array(
            'selected' => array(
                'undoredo',
                'underline',
                'specialcharacters',
            ),
        ),
    ),
    'seo' => array(
        'canonical_url' => '',
        'canonical_ssl_url' => '',
        'redirect_to_canonical_url' => 0,
        'url_rewriting' => 1,
        'tracking' => array(
            'code' => '<script>
  (function(i,s,o,g,r,a,m){i[\'GoogleAnalyticsObject\']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,\'script\',\'//www.google-analytics.com/analytics.js\',\'ga\');

  ga(\'create\', \'UA-60843674-1\', \'auto\');
  ga(\'send\', \'pageview\');

</script>',
            'code_position' => 'bottom',
        ),
    ),
    'cache' => array(
        'blocks' => false,
        'assets' => false,
        'theme_css' => false,
        'overrides' => false,
        'pages' => '0',
        'full_page_lifetime' => 'default',
        'full_page_lifetime_value' => null,
    ),
    'theme' => array(
        'compress_preprocessor_output' => false,
        'generate_less_sourcemap' => false,
    ),
    'user' => array(
        'profiles_enabled' => true,
        'gravatar' => array(
            'enabled' => false,
            'max_level' => 'g',
            'image_set' => '404',
        ),
        'registration' => array(
            'email_registration' => true,
            'type' => 'validate_email',
            'captcha' => false,
            'enabled' => true,
            'validate_email' => true,
            'approval' => false,
            'notification' => null,
            'notification_email' => false,
        ),
    ),
    'file_manager' => array(
        'restrict_uploaded_image_sizes' => true,
        'restrict_max_width' => 1170,
        'restrict_max_height' => 1000,
        'restrict_resize_quality' => 100,
    ),
    'permissions' => array(
        'model' => 'advanced',
    ),
    'debug' => array(
        'detail' => 'message',
        'display_errors' => false,
    ),
);
